### ISSUE TITLE
LibsndfileCompatibleAudioInfo leads to %CPU more than 100%

### ISSUE THREAD

**Issue by yfyeung** [lhotse-speech/lhotse#1026]
If the following condition is True, it will lead to %CPU more than 100% (like 3500%).
https://github.com/lhotse-speech/lhotse/blob/master/lhotse/audio.py#L1796-L1830

**Comment by csukuangfj** [comment]
The following gives smoe more details:

1. Even if only a single thread is used, the CPU usage in #1025 is more than 2000% from the output of htop
2. If we disable
https://github.com/lhotse-speech/lhotse/blob/7edc9aea48974b0f421bdd8ed3dfd221bdb265f8/lhotse/audio.py#L1765
then the CPU usage becomes around 100% for a single job

3. The reason is possibly due to the usage of
https://github.com/lhotse-speech/lhotse/blob/7edc9aea48974b0f421bdd8ed3dfd221bdb265f8/lhotse/audio.py#L1788-L1790

The signature of `add_basic_audio_stream`
is
https://github.com/pytorch/audio/blob/4b0254ba6365016e1fefd95afeab07ad862fadc1/torchaudio/io/_stream_reader.py#L629
```python3
    def add_basic_audio_stream(
        self,
        frames_per_chunk: int,
        buffer_chunk_size: int = 3,
        *,
        stream_index: Optional[int] = None,
        decoder: Optional[str] = None,
        decoder_option: Optional[Dict[str, str]] = None,
        format: Optional[str] = "fltp",
        sample_rate: Optional[int] = None,
        num_channels: Optional[int] = None,
    ):
```

Note that there is an option
```
        decoder_option: Optional[Dict[str, str]] = None,
```

Its explanation is given in
https://github.com/pytorch/audio/blob/4b0254ba6365016e1fefd95afeab07ad862fadc1/torchaudio/io/_stream_reader.py#L382
```python3
                In addition to decoder-specific options, you can also pass options related
                to multithreading. They are effective only if the decoder support them.
                If neither of them are provided, StreamReader defaults to single thread.

                ``"threads"``: The number of threads (in str).
                Providing the value ``"0"`` will let FFmpeg decides based on its heuristics.

                ``"thread_type"``: Which multithreading method to use.
                The valid values are ``"frame"`` or ``"slice"``.
                Note that each decoder supports different set of methods.
                If not provided, a default value is used.
```


---

I propose changing
3. The reason is possibly due to the usage of
https://github.com/lhotse-speech/lhotse/blob/7edc9aea48974b0f421bdd8ed3dfd221bdb265f8/lhotse/audio.py#L1788-L1790

to
```
 streamer.add_basic_audio_stream( 
     frames_per_chunk=int(info.sample_rate), 
     decoder_option={"threads": "1"},
 ) 
```

Maybe @yfyeung  can help test the above change and see whether it helps limit the CPU usage for a single job.

**Comment by pzelasko** [comment]
It looks like it's ffmpeg-torchaudio bindings related. CC @mthrok could you suggest anything?

**Comment by mthrok** [comment]
> It looks like it's ffmpeg-torchaudio bindings related. CC @mthrok could you suggest anything?

Unfortunately, I don't have any good suggestion on this.
I received similar report but cannot figure out what knobs I should be looking at in FFmpeg codebase. 
(it's huge and largely undocumented)

The `"threads"` option pointed above should be set to 1 by default.

https://github.com/pytorch/audio/blob/d5b2996b974b25a7c40e0673e9e71224469f9256/torchaudio/csrc/ffmpeg/stream_reader/stream_processor.cpp#L137-L140

Can I see a minimal repro? What OS and version of torchaudio is used?

**Comment by yfyeung** [comment]
> > It looks like it's ffmpeg-torchaudio bindings related. CC @mthrok could you suggest anything?
> 
> Unfortunately, I don't have any good suggestion on this. I received similar report but cannot figure out what knobs I should be looking at in FFmpeg codebase. (it's huge and largely undocumented)
> 
> The `"threads"` option pointed above should be set to 1 by default.
> 
> https://github.com/pytorch/audio/blob/d5b2996b974b25a7c40e0673e9e71224469f9256/torchaudio/csrc/ffmpeg/stream_reader/stream_processor.cpp#L137-L140
> 
> Can I see a minimal repro? What OS and version of torchaudio is used?

@mthrok Sure
pip install lhotse
```python
i = 0
while True:
recording = Recording.from_file(
    path="example.mp3",
    recording_id=i,
)
i = i + 1
```
htop, seeing CPU% more than 3500%
