### ISSUE TITLE
Experiencing memory leakage with MixedCut.load_audio

### ISSUE THREAD

**Issue by hereismohsen** [lhotse-speech/lhotse#1333]
For debugging purposes, I'm working with a very small dataset (180 training samples, and 30 validation samples all of which are below 30s). I load my manifest lazily and want to do processing on the fly. During training, my RAM memory(68.7G) is getting full until the program causes OOM error and it cannot even fully train on a single batch. I tried to find the source of this issue and it seems that it's related to the _MixedCut.load_audio()_ function (just loading the cut without extracting feature) or any function that uses it. When I comment _MixedCut.load_audio_ functions in __getitem__() of my dataset, the problem resolves. I tried using different samplers (DynamicBucketingSampler or SimpleCutSampler) and was still there. Decreasing the num_worker reduces the growing rate of the memory a little bit but according to my dataset, the memory growth (at least 20 to 30 GB) should not occur at all.

**Comment by hereismohsen** [comment]
I think I found out what was the problem. I'd written a custom transform class like CutReverb. In this class I'd put this line and my memory profile was showing something like this:
`temp_cut=temp_cut.perturb_speed(rng.uniform(0.9, 1.1))`
![uniform](https://github.com/lhotse-speech/lhotse/assets/42408282/cc2c4c74-482c-46af-8940-56ddd0bb354b)
When I changed the line to this the problem was solved:
`temp_cut=temp_cut.perturb_speed(rng.choice([0.9, 1.1]))`
![choice](https://github.com/lhotse-speech/lhotse/assets/42408282/d9daf62d-2fcc-4a75-9fec-70586376835a)

I don't know why perturbing a cut's speed with high precision floats (unlike exact floats like 1.1) tasks this much memory and whether it is fixable or not.

**Comment by pzelasko** [comment]
Speed perturbation uses resampling. In order to optimize resampling, we cache the resampling kernel coefficients to be re-used across invocations. If you provide a different speed perturb factor every time, it will have to compute a new resampling kernel for that. https://github.com/lhotse-speech/lhotse/blob/4f014b13202c724d484e0471343053a261487b8a/lhotse/augmentation/torchaudio.py#L69-L83

If you want to keep randomized speed perturb factor, you’d have to disable the caching (there is no option to disable it right now).

As a side note, resampling with very large ratios between source and target SR is difficult as the kernels may become very large.
