### ISSUE TITLE
Feature request: Add json support for CutSet manifests

### ISSUE THREAD

**Issue by janvainer** [lhotse-speech/lhotse#143]
Could we have json support for CutSets? Right now, only `to_yaml` creates files with correct information, while `to_json` does not contain feature info. It would not matter much, but loading the yaml file takes a long time for datasets with hundreds of hours. Is there a reason why `to_json` is not supported? If not, I can make a PR to add it.

**Comment by pzelasko** [comment]
That doesn't sound right. I just double-checked with some data I'm working on right now:
![image](https://user-images.githubusercontent.com/15930688/99818633-75c73400-2b1c-11eb-91b2-e8fa02096fe5.png)

Is it possible that you are not assigning the result of `compute_and_store_features` to a new variable? That method does not modify the `CutSet` in-place because that'd impossible to do if it contained `MixedCut`s.

**Comment by janvainer** [comment]
Hm I will try to replicate this code and let you know.

**Comment by pzelasko** [comment]
@janvainer Were you able to work it out? Can we close this issue?

**Comment by janvainer** [comment]
Hi, sorry for the delay. I just checked with the LJSpeech dataset and it works like a charm. I was having some struggle back then with custom data, but I think I was not storing the CutSet at the correct point in the script. We can close this now.
