### ISSUE TITLE
Feature: AudioCutting feature extractor

### ISSUE THREAD

**Issue by janvainer** [lhotse-speech/lhotse#150]
Is it possible right now to use CutSet to cut all recordings into separate wav files and dump these files on disk?
If not, would it be a considerable feature?

It could be used in a similar way to feature extraction.
```
recording_set = RecordingSet.from_yaml('audio.yml')
audio_cutter = AudioCutter()

with AudioWriter() as storage:
    builder = FeatureSetBuilder(feature_extractor=audio_cutter, storage=storage)
    feature_set = builder.process_and_store_recordings(
        recordings=recording_set,
        num_jobs=8
    )
```
or the cutset would simply have a function `CutSet.cut_audio(path)` or similar.
The audio cuts could be stored in subfolders of path based eg on recording name. Along with the wav cuts, there would also be a manifest file for the Cuts. Let me know if this would be of interest or if something similar is already possible. Thanks

**Comment by pzelasko** [comment]
That's a cool idea. Since `CutSet` has `compute_and_store_features` already, we could add `compute_and_store_recordings` to it, with the same API (minus minor modifications):

```python
def compute_and_store_recordings(
    self,
    output_dir: Pathlike,
    executor: Optional[Any] = None,
    augment_fn: Optional[AugmentFn] = None
) -> 'CutSet':
```

I think we'll eventually have different classes for `AudioStorage` but at this point it's fine to just support a path to a directory. The `executor` thing is nice because it allows you to choose between no parallelism, multithreading, multiprocessing and distributed processing (e.g. with Dask). I think having `augment_fn` is beneficial in case you want to leverage WavAugment/Torchaudio integration into Lhotse to transform your data before saving.

It should return a `CutSet` that "converted" every `MixedCut` to a simple `Cut`, since the audio files contain mixes after doing that.

WDYT? Want to have a go at it? :)

**Comment by danpovey** [comment]
Might be nice to have one place where "executor" is documented in full, and
have the documentation for individual uses explain it very briefly and
refer to that.
Possibly the same for other concepts.  Just an idea.

**Comment by pzelasko** [comment]
Thanks @danpovey - I opened an issue for that #152

**Comment by janvainer** [comment]
@pzelasko being able to use augmentations and using parallel execution is a really cool idea I think. 
Sure I will give it a try. Just a question - what should be the dir structure for saving? By recordings or perhaps by speakers? The latter would not work if the data had no speaker annotations. So by recording would probably make most sense. We could also do it bu Cuts though.

**Comment by pzelasko** [comment]
I think we can mimic the approach we took in saving the feature matrices to files, i.e. use the first three symbols from the Cut ID as a name for the sub-directory, and store the new recording (with name == cut ID) in it. 

Maybe we can save it as a FLAC rather than WAV to save some space - I think it’s supported by soundfile out-of-the-box.

So e.g. for cuts with IDs:

- abc12345
- abc34576
- abd23452

we’d create the following structure:

my_output_dir
|— abc
|  |— abc12345.flac
|  |— abc34576.flac
|— abd
   |— abd23452.flac

You can find code that does a similar thing in the `LilcomFilesWriter` class.

**Comment by janvainer** [comment]
Agree, sorry for late response. I was quite busy before Christmas. I can give it a try, but probably in a few weeks from now.
