### ISSUE TITLE
why batch.features shape is not equal to batch.supervisions.text length?

### ISSUE THREAD

**Issue by hegc** [lhotse-speech/lhotse#184]
When I set the max_frames=90000 and max_cuts=100, then the shape of batch.features is [99, 1107, 40], the length of texts list is 100？

**Comment by pzelasko** [comment]
That's most likely because you have `concat_cuts` option set to `True`, which means that it will try to pack multiple cuts into a single "sample" in the batch with some silence in between. You can verify by checking that the `sequence_idx` field has some values that are duplicate (read it like: the `text` as index `i` is corresponding to the feature matrix at `sequence_idx[i]`, starting at `start_frame[i]` and with length of `num_frames[i]`). You can disable this setting with `concat_cuts=False`.

**Comment by hegc** [comment]
Great, I guess I get it! Thanks.
