### ISSUE TITLE
Question RE getting features with & without MUSAN augmentation

### ISSUE THREAD

**Issue by danpovey** [lhotse-speech/lhotse#439]
Is it possible to get, in parallel, the features for a minibatch with and without MUSAN augmentation?

**Comment by pzelasko** [comment]
Yes. The easiest way to do this is to copy the `K2SpeechRecognitionDataset` class and modify the code in `__getitem__`:

https://github.com/lhotse-speech/lhotse/blob/8c7e43f152efd76dc589175aa43e28135885dd97/lhotse/dataset/speech_recognition.py#L98-L101

By adding the following line:

```python
# This data is before any augmentation
inputs_raw, _ = self.input_strategy(cuts)

# This code is untouched
for tnfm in self.cut_transforms: 
    cuts = tnfm(cuts) 
```

And then extend the `batch` dict below with:

```python
        batch = {
            "inputs": inputs,
            "inputs_raw": inputs_raw,  # <-- this is new
            "supervisions": default_collate(
            ...
```

Note: this is inefficient because it performs extra I/O, but it's really the simplest. I have an idea how to add a caching mechanism to make these type of operations zero-overhead in terms of I/O, I'll try to add it soon.

**Comment by pzelasko** [comment]
BTW I think going forward in Icefall, it actually makes sense to move/copy the dataset class from Lhotse, remove most of the generic stuff, and for each type of training just create a new, modified Dataset copy with hardcoded transforms etc. It will make the data processing flow easier to understand.

**Comment by pzelasko** [comment]
Check out #443, which should remove the speed penalty from the steps I described before.

**Comment by pzelasko** [comment]
Can we close this (with an example provided and the caching mechanism in place)?
