### ISSUE TITLE
Why this project is named 'lhotse'

### ISSUE THREAD

**Issue by Owen864720655** [lhotse-speech/lhotse#456]
Hi, 

what does the project name stand for?

**Comment by csukuangfj** [comment]
I think one of its meaning is the name of a mountain.

Note k2 is also the name of a mountain.

**Comment by pzelasko** [comment]
At the beginning of the “next-generation Kaldi” project Dan decided to name it k2, which happens to be a word-play: abbreviation of “Kaldi 2” and the name of the world’s second largest mountain. Since we wanted to have multiple libraries rather than one big framework, we decided to name them after other “neighbouring” mountains :)

**Comment by mthrok** [comment]
BTW I'm curious about the release names as well.

https://github.com/lhotse-speech/lhotse/releases

**Comment by pzelasko** [comment]
The release names are loosely related to a mix of mountain climbing, Himalayas, ice/snow, season of the year, and my own inspirations at the moment of releasing.
