### ISSUE TITLE
__len__ function for samplers? 

### ISSUE THREAD

**Issue by LasseWolter** [lhotse-speech/lhotse#605]
Is there a reason why samplers define the `num_cuts` property but don't implement the `__len__` method? 

Seems more intuitive to me to access the value of `num_cuts` through a `__len__` method.

**Comment by csukuangfj** [comment]
> Is there a reason why samplers define the num_cuts property

Also, not all samplers return meaningful value for `num_cuts`. If CutSet is read in lazy mode, for instance, it will return `None` for  the property`num_cuts`

**Comment by LasseWolter** [comment]
alright, that makes sense. I'm pretty new to ML and was just was wondering about this because the lhotse datasets don't have a `__len__` function which is usually the case for pytorch datasets, if I'm not mistaken (see https://pytorch.org/tutorials/beginner/basics/data_tutorial.html#creating-a-custom-dataset-for-your-files).

In this talk (https://youtu.be/-NUpzHo_y-w?t=1806) @pzelasko mentioned that:
> it's the sampler that actually owns all the metadata 

Possibly this could be mentioned more explicitly in the documentation?

**Comment by pzelasko** [comment]
`__len__` is unfortunately a huge pitfall for at least two reasons:
- our batch size is dynamic -- in order to know the number of batches, you need to iterate the whole sampler first
- if you're working with larger datasets, you might want to read the manifests lazily, so again knowing how much data you have requires iterating the whole manifest.

Good suggestions about improving the docs on this. Would be great if you could do it as you have a fresh perspective on this -- otherwise I'll add this to my docs-improvement list and hopefully make the change one day.

**Comment by LasseWolter** [comment]
> our batch size is dynamic -- in order to know the number of batches, you need to iterate the whole sampler first

so does calling `num_cuts` do that each time I call it?

**Comment by LasseWolter** [comment]
Please add it to your doc-list for now: 
1. I'm working on the final bits of my dissertation this month. 
2. I'm not entirely sure about the dynamic loading and use of `DataSource` class. 

Thanks for the discussion, if I get back to this after my dissertation I'll let you know. 
Closing issue for now.
